keiba_forecast/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('keiba_forecasts.urls')),
]

keiba_forecasts/urls.py
from django.contrib import admin
from django.urls import path, include


from . import views


app_name = 'keiba_forecasts'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('blogs/', views.blogs, name='blogs'),
    path('blogs/<int:blog_id>', views.blog, name='blog'),
    path('blogs/<int:blog_id>/comments/', views.comments, name='comments'),
    path('dopester/', views.dopester, name='dopester'),
]

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

keiba_forecasts/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Blog(models.Model):
    title = models.CharField('タイトル', max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    text = models.TextField('本文')
    date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title


class Comment(models.Model):
    name = models.CharField('名前', max_length=200)
    text = models.TextField('コメント')
    date = models.DateTimeField(auto_now_add=True)
    blog = models.ForeignKey(Blog, related_name='comments', on_delete=models.CASCADE)


    def __str__(self):
        return self.text


class Post(models.Model):
    text = models.TextField('コメント')
    date = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.text

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

keiba_forecasts/forms.py
from django.db.models import fields
from keiba_forecasts.models import Comment
from django import forms
from .models import Comment, Post


class RaceForm(forms.Form):
    year = forms.CharField(label='year', max_length=4, initial='2021')
    c_place = []
    p_name = ['札幌','函館','福島','新潟','東京','中山','中京','京都','阪神','小倉']
    for p in p_name:
        c_place.append((p,p))
    place = forms.ChoiceField(label='開催', initial='東京', choices=c_place)
    c_num = []
    for i in range(1,7):
        c_num.append((str(i),str(i)))
    num = forms.ChoiceField(label='回', initial='1', choices=c_num)
    c_day = []
    for i in range(1,13):
        c_day.append((str(i),str(i)))
    day = forms.ChoiceField(label='日目', initial='1', choices=c_day)
    c_race = []
    for i in range(1,13):
        c_race.append((str(i),str(i)))
    race = forms.ChoiceField(label='R', initial='1', choices=c_race)


class CommentForm(forms.ModelForm):
        class Meta:
            model = Comment
            fields = ['name','text']


class PostForm(forms.ModelForm):
        class Meta:
            model = Post
            fields = ['text']

keiba_forecasts/views.py
from django.shortcuts import render, redirect

from .forms import RaceForm, CommentForm, PostForm

from .models import Blog, Comment, Post

# Create your views here.
def index(request):
    if request.method == 'POST':
        form = RaceForm(request.POST)
        content_dict = {'form':form}
        content_dict['year'] = request.POST.get('year', None)
        content_dict['place'] = request.POST.get('place', None)
        content_dict['num'] = request.POST.get('num', None)
        content_dict['day'] = request.POST.get('day', None)
        content_dict['race'] = request.POST.get('race', None)


        place_list = ['札幌','函館','福島','新潟','東京','中山','中京','京都','阪神','小倉']
        i = 1
        for p in place_list:
            if content_dict['place'] == p:
                place_num = i
            i += 1
        
        if place_num < 10:
            place_num = '0' + str(place_num)
        else:
            place_num = str(place_num)

        if int(content_dict['num']) < 10:
            num = '0' + content_dict['num']
        else:
            num = content_dict['num']

        if int(content_dict['day']) < 10:
            day = '0' + content_dict['day']
        else:
            day = content_dict['day']

        if int(content_dict['race']) < 10:
            race = '0' + content_dict['race']  
        else:
            race =  content_dict['race']
        
        year = str(content_dict['year'])
        race_id = year + place_num + num + day + race
        

        src = f'/static/deployment/{race_id}deployment.png'

        place = content_dict['place']
        content_dict['info'] = f'{year}年 {place} {num}回 {day}日目 {race}R'
        content_dict['src'] = src
        content_dict['id'] = race_id
    else:
        form = RaceForm()
        content_dict = {'form':form}


    return render(request, 'keiba_forecasts/index.html', content_dict)


def about(request):
    return render(request, 'keiba_forecasts/about.html')


def blogs(request):
    blogs = Blog.objects.order_by('-date')
    context = {'blogs':blogs}
    return render(request, 'keiba_forecasts/blogs.html', context)


def blog(request, blog_id):
    blog = Blog.objects.get(id=blog_id)
    context = {
        'blog':blog,
        'text':blog.text,
        'date':blog.date,
        'comments':blog.comments,
    }
    c_num = blog.comments.count()
    context['c_num'] = c_num
    form = CommentForm()
    context['form'] = form
    return render(request, 'keiba_forecasts/blog.html', context)


def comments(request, blog_id):
    blog = Blog.objects.get(id=blog_id)

    if request.method != 'POST':
        form = CommentForm()
    else:
        form =CommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.blog = blog
            new_comment.save()
            form = CommentForm()
    comments = blog.comments.order_by('-date')
    context = {'comments':comments}
    context['form'] = form
    context['blog'] = blog
    return render(request, 'keiba_forecasts/comments.html', context)


def dopester(request):
    #予想家掲示板を表示
    posts = Post.objects.order_by('-date')
    if request.method != 'POST':
        form = PostForm()
    else:
        form = PostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.created_by = request.user
            new_post.save()
            form = CommentForm()
            return redirect('keiba_forecasts:dopester')
    
    context = {'posts':posts}
    context['form'] = form
    return render(request, 'keiba_forecasts/dopester.html', context)

users/views.py
import keiba_forecasts
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('keiba_forecasts:dopester')
    
    context = {'form':form}
    return render(request, 'registration/register.html', context)

keiba_forecasts/templates/keiba_forecasts/about.html
{% extends 'keiba_forecasts/base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}
  <img src='/static/image/about.png' / class="img-fluid" alt="Responsive image">
{% endblock content %}

keiba_forecasts/templates/keiba_forecasts/base.html
{% load bootstrap4 %}
{% load static %}

<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>すがの競馬展開予想</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}" media="screen and (min-width:992px)">
    <link rel="stylesheet" href="{% static 'css/mobile.css' %}" media="screen and (max-width:991px)">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light" >
      <a class='navbar-brand' style='color:rgb(160, 80, 0);' href='{% url "keiba_forecasts:index" %}'>
        すがの競馬展開予想
        <img src="/static/image/9547.png" width="30" height="30" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <a class="nav-link" style='color: white;' href='{% url "keiba_forecasts:index" %}'>TOP</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" style='color: white;' href='{% url "keiba_forecasts:about" %}'>使い方</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" style='color: white;' href='{% url "keiba_forecasts:blogs" %}'>ブログ</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" style='color: white;' href='{% url "keiba_forecasts:dopester" %}'>予想家掲示板</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class='jumbotron'>
      {% block content %}{% endblock content %}
    </div>
    
  </body>
</html>

keiba_forecasts/templates/keiba_forecasts/blog.html
{% extends 'keiba_forecasts/base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}
  <h2><a href="{% url 'keiba_forecasts:blogs' %}">ブログ一覧</a></h2>
  <h5>{{blog}}</h5>
  <p>{{text|linebreaks}}</p>
  <p>{{date}}</p>
  <a href='{% url "keiba_forecasts:comments" blog.id %}'>コメント [{{c_num}}]</a>
{% endblock content %}

keiba_forecasts/templates/keiba_forecasts/blogs.html
{% extends 'keiba_forecasts/base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}
  <h2>ブログ一覧</h2>
    <ul>
      {% for blog in blogs %}
        <li><p><a href='{% url "keiba_forecasts:blog" blog.id %}'>{{blog}}</a><span class='b_date'>　{{blog.date}}作成</span></p></li>
      {% empty %}
        <li>記事はまだありません</li>
      {% endfor %}
    </ul>
{% endblock content %}

keiba_forecasts/templates/keiba_forecasts/comments.html
{% extends 'keiba_forecasts/base.html' %}
{% load bootstrap4 %}
{% load static %}

<p>a</p>
{% block content %}
  <a href='{% url "keiba_forecasts:blog" blog.id %}'>記事に戻る</a>
  <form action='{% url "keiba_forecasts:comments" blog.id %}' method="POST" class="mb-3">{% csrf_token %}
    {% bootstrap_form form %}
    <div >
        <button type="submit" class="btn btn-secondary">コメントを書く</button>
    </div>
  </form>
  <h3>コメント</h3>
    <div class='comments'>  
        <ul>
        {% for comment in comments %}
            <div class='comment'>
                <li class='comment_name'>{{comment.name}}さん  <span class='comment_date'>{{comment.date}}</span></li>
                <li class='comment_text'>{{comment.text}}</li>
            </div>
        {% empty %}
            <div class='comment'>
                <li>コメントはまだありません</li>
            </div>
        {% endfor %}
        </ul>
    </div>
{% endblock content %}

keiba_forecasts/templates/keiba_forecasts/dopester.html
{% extends 'keiba_forecasts/base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}
  <h2>予想家掲示板</h2>
  {% if not user.is_authenticated %}
  <p>投稿には予想家登録が必要です。</p>
  <a class='auth' href='{% url "users:register" %}'>予想家登録</a>
  <a class='auth' href='{% url "users:login" %}'>ログイン</a>
  {% else %}
  <a class='auth' href='{% url "users:logout" %}'>ログアウト</a>
  <form action='{% url "keiba_forecasts:dopester" %}' method="POST" class="mb-3">{% csrf_token %}
    {% bootstrap_form form %}
    <div >
        <button type="submit" class="btn btn-secondary">投稿</button>
    </div>
  </form>
  {% endif %} 
  <ul>
    {% for post in posts %}
      <li><p class='dope_name'>{{post.created_by}}さん <span class='dope_date'>{{post.date}}</span></p></li>
      <li><p class='dope_text'>{{post}}</p></li>
    {% empty %}
      <li>記事はまだありません</li>
    {% endfor %}
  </ul>

{% endblock content %}

keiba_forecasts/templates/keiba_forecasts/index.html
{% extends 'keiba_forecasts/base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}
  <div class='leads'>
    <p class="lead">
    今週行われるレースの展開を予想します。<br>
    <span class='attention'>※更新は馬番確定後</span></p>
    <p>開催情報はこちらから→<a class='jra-link' href='https://www.jra.go.jp/'>JRA公式HP</a></p>
  </div>
  <form method="POST" class="mb-3">{% csrf_token %}
    {% bootstrap_form form %}
    <div >
        <button type="submit" class="btn btn-success">予想する</button>
    </div>
  </form>
  <p>{{ info }}</p>
  <img src={{src}} / class="img-fluid" alt="Responsive image">
{% endblock content %}

keiba_forecasts/templates/keiba_forecasts/test.html
{% load static %}
{% load bootstrap4 %}
<html>
    <head>
        <title>すがの競馬展開予想</title>
    </head>
    <body>
        <h1>すがの競馬展開予想</h1>
        <h2>予想するレース</h2>
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">予想する</button>
        </form>
        <p>{{year}}年 {{place}} {{num}}回 {{day}}日目 {{race}}R</p>
        <img src={{src}} />
    </body>

</html>